### ISSUE TITLE
acess device from wlan ? external network

### ISSUE THREAD

**Issue by mirsella** [dickydoouk/tp-link-tapo-connect#13]
hey I got a tapo 100
I managed to get this package working on LAN by accessing the device with it's local IP.
do you have a idea if it would be possible to connect directly to p100 from another network ? 

my current solution is a web server listening on a PC in my home and relaying the info to the device with this package.

**Comment by mirkokiefer** [comment]
The official Tapo app works without being connected to the local network - so there must be APIs for that. Looking for a solution as well!

**Comment by dewhurstwill** [comment]
I will have a look into this however even with inspecting network traffic this will be a difficult task as the mobile app and API is not documented. If they had a desktop or webapp this would be much easier.

In the meantime I would advise a solution where you run your own rest API locally on a lower power computer like a raspberry pi, setting up dynamic DNS and opening a port on your router. If you want the solution to be more secure you could implement authentication on your rest api which passes the credentials through to the tapo library instead of them being environment variables.

**Comment by mirsella** [comment]
yeah I'm already using this solution https://github.com/mirsella/tp-link-tapo-connect-wrapper

thanks for the answer

**Comment by dewhurstwill** [comment]
In the meantime package my work slightly better for your requirements https://github.com/adumont/tplink-cloud-api

**Comment by mirsella** [comment]
@dewhurstwill this project would be perfect except it doesn't support the P100, a issue is open about it on the project page.

**Comment by dickydoouk** [comment]
It would be ideal if the tp-link cloud api supported passthrough to the smart plug which it may do (Just haven't found out how this is done as yet)
