### ISSUE TITLE
loginDevice is not working

### ISSUE THREAD

**Issue by palatinb** [dickydoouk/tp-link-tapo-connect#19]
Hello,

I'm trying to use your library, but when i use loginDevice method. I dit not get back any information from the device. 
Firstly I just setup a simple example based on your readme so nothing serious but I did not get back information it look like it is still runing but does nothing.
If I use loginDeviceByIp it works properly.

Could you pelase help me what can cause this?

Thanks,
Bence

**Comment by dickydoouk** [comment]
If you know your device IP address then use loginDeviceByIp.

The loginDevice method performs a reverse IP lookup using the MAC from the TapoDevice object as returned by listDevices method (This is because the cloud methods do not return local IP addresses of the devices, just the mac is returned).

The reverse lookup is a bit flakey and depends on how recent your ARP device table is. You can diagnose if your device is listed by running `> arp -an` on the command line.

The simplest way to update your arp table is to ping your device but to do this you will need to know your ip address (Goto 0)

Hopefully that explains things

**Comment by dickydoouk** [comment]
Closed presumably resolved
