### ISSUE TITLE
tapo.cloudLogin get Error: Unexpected Error Code: -20004

### ISSUE THREAD

**Issue by coffeemilkcrazy** [dickydoouk/tp-link-tapo-connect#22]
Today I just got the error after call tapo.cloudLogin always got error message Error: Unexpected Error Code: -20004 and cannot login, not sure what error -20004 code mean? 

Could you please check this error? hope we can fix it

**Comment by avalkowsky** [comment]
+1 also observed that one and have no clue what is it about

**Comment by rpalfray87** [comment]
Same for me.
Apparently the message means: "API rate limit exceeded"
But I don't know how to solve it :/

**Comment by timrogers** [comment]
I've fixed this in #24 by automatically generating a UUID on each request, rather than using the hard-coded one - we just need to wait for @dickydoouk to have the time to review it 😊 

If you want to give my changes a try in the mean time, then you can install my version of the package by running `npm install timrogers/tp-link-tapo-connect#random-uuid`.

**Comment by rpalfray87** [comment]
> I've fixed this in #24 by automatically generating a UUID on each request, rather than using the hard-coded one - we just need to wait for @dickydoouk to have the time to review it blush
> 
> If you want to give my changes a try in the mean time, then you can install my version of the package by running `npm install timrogers/tp-link-tapo-connect#random-uuid`.

It works for me. Thank you :)
